services:
  - type: web
    name: m3u8-extractor
    env: node
    plan: free
    region: oregon
    buildCommand: |
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
