services:
  - type: web
    name: m3u8-extractor
    env: node
    plan: free
    buildCommand: |
      yarn install
      yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
